### PR TITLE
Major Updates

### PR DESCRIPTION
**Pull request by Aganonce**
Adds Object Builder and Object models. Adds Interaction Model (GitHub-specific) that mediates actions between objects and agents. Adds config file (later database) that controls all attributes to objects and agents that is processed via the Analysis Library.

### CODE REVIEW

**Comment by haoyifan** [comment]
Hey James,

Thanks a lot for the updates. Those updates regarding analysis_lib and config.json is extremely useful. Here're something I want to discuss with you:

1. I noticed you query user attributes in AgentBuilder, then pass it into Agent when instantiate it. I'm not sure if that's a scalable design because AgentBuilder will need to be Agent Class aware in order to query social media specific attributes. Instead, if Agent is responsible for querying whatever attributes it need, AgentBuilder won't need much changes when we switch to other social media.

2. For Object Builder, we think it might not be necessary in the future (because we can also model Object with Agent). This might come in handy because evaluation code has user centric metrics and repo centric metrics. Modeling objects within Agent might make more sense in this settings. However, if there're other benefits provided by this separation, please let me know.

3. I'm a little bit confused with Interaction model. Can you elaborate on that more?

**Comment by Aganonce** [comment]
Here are the answers to your questions:

1. I was thinking of initializing the agents with all their attributes makes it easier to represent how an agent evolves with each time step. Having all attributes on hand saves us time because it won't need to query attributes through some pipeline at every step. In terms of scalability the attributes are drawn straight from the database, so any changes to that will be reflected immediately. If we want to keep the agent model even more general, we can define overarching types of actions (like actions you can only do once, versus actions that can be done multiple times, versus actions that result in generating new objects) and simply have the interaction model handle everything media-specific.

2. You're right, we can totally model the objects as agents. I will take a look at that.

3. The interaction model is in charge of handling the media-specific features of actions. We can't have the simulation be completely general, because then unique actions like pull requests could never be modeled. The interaction model essentially has a list of action types specific to its media type and updates the agents and their agent list at each time step given the action that results from the probability distribution. In terms of scalability, the interaction model can easily be switched out for a new one, and as long as we keep the agent model, agent builder, behavior model, and simulation core general then we will only ever need to fiddle with the analysis libraries and the interaction model. If you can think of a better way of accounting for media-specific actions without hard-wiring them into the simulation please let me know.

**Comment by haoyifan** [comment]
1. One other thing that I'm worried about is that passing attributes from AgentBuilder to Agent lacks the flexibility. If this procedure is placed in Agent class, when we implement new Agent Model, it can essentially queries whatever it needs and do whatever preprocessing it wants. Besides, if attributesList becomes large and part of them are not necessary for analysis, simply dragging all of them to Agent might be a problem for large scale simulation. Tying that procedure to AgentBuilder might restrict the development for future Agent Model. I personally haven't came up with any scenario where Agent Model needs this flexibility, but I think it might be better to leave this space for future developers.

2. Can you merge methods that Object might need into Agent class, and delete Object related code and commit again? That can be included in this pull request.

3. Yeah I get the idea of interaction model. It's not yet included in our current architecture though. Just help me to understand, can you explain why pull request is media-specific and therefore needs special processing? What're the differences between pull request and other github actions that are media-nonspecific?

**Comment by Aganonce** [comment]
1. This isn't a question of preprocessing, but individuality. We need to keep a record of each agent's attributes so that we can use them in the evaluation code that was provided to us. Having each agent keep those attributes on themselves is just easy to visualize. However, if we want a middle-ground, I can set it up so that each agent can directly query the database, where we can save the attributes. We can have a table that contains all initial attributes that will be updated by the simulation over time. However, I should mention that unless each agent had a couple thousand attributes, the simulation will not slow due to agent count. In fact, if there were enough agents, there would be no complexity difference between the two options.
2. I am doing that now.
3. A pull request generates an entirely new object (that has completely different attributes to either a user or a repo). This new object (a gate node) only accepts certain actions and emits a special action itself once its been acted upon by a specific type of user. I can figure out a way to generalize this so we need only one kind of interaction model if we really need to, but I definitely want to keep the interaction model itself. If anything, its a nice form of componentization that keeps the list of actions and reactions partitioned away.

**Comment by Aganonce** [comment]
I made the changes. However, I have kept the agent class attributes. I will replace that with attribute querying once I've set up the database and have interfaced the data cube.

You guys will have to deal with the remaining merge conflict.

**Pull request closed without merging**
